### ISSUE TITLE
Script repos should be combined instead of separated

### ISSUE THREAD

**Issue by Snepsts** [w-w-wood-products-inc/Script-AzureStorageCopyBlobByMetadata#1]
Hi guys, I have a question:

Is there a reason we have repos dedicated to scripts, while also being prepended with script? Perhaps it would make more sense to make an AzureScripts repo and organize by folder? Just a question with the intention of reducing bandwidth and consolidating naming/logic.

For many cases, script repos are combined to utilize github's repo service, otherwise they are made to be gists.

That is all. Great work by the way!

**Comment by kaburkett** [comment]
I wish github orgs could have gists

**Comment by kaburkett** [comment]
We could combine these. You should make a PR and we add you in the org.

**Comment by Snepsts** [comment]
@kaburkett Opened a PR

**Comment by kaburkett** [comment]
Thanks! I'll merge when I'm at a computer.

**Comment by kaburkett** [comment]
Also I will send an invite to our org. Thanks for the PR

**Comment by Snepsts** [comment]
Aw heck yeah bro

**Comment by kaburkett** [comment]
Merged, approved, and invite to contributors sent.
